name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Setup Docker
        uses: postman/newman
      - name: Run Collection
        run: |
          newman run collections/Google\ Places\ API.postman_collection.json