name: CI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Newman
      run: |
            npm install newman
    - name: Run Collection
      run: |
            newman run collections/Google\ Places\ API.postman_collection.json