name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: postman/newman
    # - name: Install Newman
    #   run: |
    #     npm install newman
    - name: Run Collection
      run: |
        newman run collections/Google\ Places\ API.postman_collection.json